version: '3.8'
services:
  mongo:
    image: mongo
    container_name: my_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_URI=mongodb://localhost:27017/test_db

volumes:
  mongodb_data: {}
